# Generated by Django 4.2.6 on 2023-11-21 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicename', models.CharField(default='LED', max_length=255)),
                ('devicestatus', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20, null=True)),
                ('parameter', models.JSONField(blank=True, null=True)),
                ('devicemode', models.IntegerField(blank=True, default=1, null=True)),
                ('openTime', models.DateTimeField(blank=True, null=True)),
                ('closeTime', models.DateTimeField(blank=True, null=True)),
                ('boxid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inwhichbox', to='boxes.box')),
            ],
        ),
    ]
