# Generated by Django 4.2.6 on 2023-11-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='devicemode',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
