# Generated by Django 4.2.6 on 2023-11-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_devicemode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='closeTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='openTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
