# Generated by Django 4.2.6 on 2023-12-01 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_closetime_alter_device_opentime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='closeTime',
            new_name='closetime',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='openTime',
            new_name='opentime',
        ),
    ]
