# Generated by Django 4.2.6 on 2023-11-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_watertemp', models.JSONField(blank=True, null=True)),
                ('b_airtemp', models.JSONField(blank=True, null=True)),
                ('b_humidity', models.JSONField(blank=True, null=True)),
                ('b_oxygen', models.JSONField(blank=True, null=True)),
                ('b_co2', models.JSONField(blank=True, null=True)),
                ('b_ec', models.JSONField(blank=True, null=True)),
                ('b_ph', models.JSONField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('method', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
