# Generated by Django 4.2.6 on 2023-11-21 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='growthIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('airtemp', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('luminance', models.FloatField(blank=True, null=True)),
                ('ledrgb', models.JSONField(blank=True, null=True)),
                ('sunlong', models.FloatField(blank=True, null=True)),
                ('cur_Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('boxid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whichbox', to='boxes.box')),
            ],
        ),
    ]
