# Generated by Django 4.2.6 on 2023-12-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growthsIN', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthin',
            name='cur_Image',
            field=models.ImageField(blank=True, null=True, upload_to='growin/'),
        ),
    ]
